site_name: 3DS Troubleshooter
site_description: Interactive troubleshooter for 3ds.hacks.guide.
theme:
  name: material
  custom_dir: theme
  features:
    - navigation.top
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
    - admonition
    - tables
    - pymdownx.tilde
    - attr_list
    - md_in_html
    - pymdownx.emoji:
       emoji_index: !!python/name:materialx.emoji.twemoji
       emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - include-markdown
  - literate-nav:
      nav_file: nav.md